# Generated by Django 2.1.5 on 2019-04-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0004_auto_20190412_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqscore',
            name='usermcq',
            field=models.CharField(max_length=2000, verbose_name='usermcq'),
        ),
    ]
