# Generated by Django 2.1.5 on 2019-03-31 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20190331_0832'),
        ('subjective', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsub',
            options={'verbose_name': 'Subjective Question', 'verbose_name_plural': 'Subjective Questions'},
        ),
        migrations.RemoveField(
            model_name='questionsub',
            name='id',
        ),
        migrations.RemoveField(
            model_name='questionsub',
            name='ques_image',
        ),
        migrations.RemoveField(
            model_name='questionsub',
            name='ques_link',
        ),
        migrations.RemoveField(
            model_name='questionsub',
            name='ques_text',
        ),
        migrations.AddField(
            model_name='questionsub',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.Question'),
            preserve_default=False,
        ),
    ]
