# Generated by Django 2.1.5 on 2019-03-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjective', '0002_auto_20190331_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersub',
            name='question',
        ),
        migrations.DeleteModel(
            name='AnswerSub',
        ),
    ]
