# Generated by Django 2.1.5 on 2019-04-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjective', '0004_answersub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsub',
            options={},
        ),
    ]
