# Generated by Django 2.1.5 on 2019-04-02 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjective', '0005_auto_20190401_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsub',
            options={'verbose_name': 'Subjective Question', 'verbose_name_plural': 'Subjective Questions'},
        ),
    ]
