# Generated by Django 2.1.5 on 2019-04-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjective', '0006_auto_20190402_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionsub',
            options={},
        ),
    ]
