# Generated by Django 2.1.5 on 2019-04-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjective', '0007_auto_20190402_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usersub', models.CharField(max_length=2000, verbose_name='usermcq')),
                ('subscore', models.IntegerField(default=0, verbose_name='userscore')),
            ],
        ),
    ]
