# Generated by Django 2.1.5 on 2019-04-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjective', '0008_subscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscore',
            name='usersub',
            field=models.CharField(max_length=2000, verbose_name='usersub'),
        ),
    ]
