# Generated by Django 2.1.5 on 2019-04-12 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjective', '0009_auto_20190405_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersub',
            name='user_ans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='userbyans'),
        ),
        migrations.AlterField(
            model_name='subscore',
            name='usersub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usersub'),
        ),
    ]
