# Generated by Django 2.1.5 on 2019-04-13 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjective', '0012_subscore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersub',
            name='answermarks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answersub',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
