# Generated by Django 2.1.5 on 2019-03-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_text', models.CharField(max_length=3000, verbose_name='your answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_no', models.IntegerField(verbose_name='Question Number')),
                ('ques_text', models.CharField(max_length=2000, verbose_name='text')),
                ('ques_image', models.FileField(upload_to='')),
                ('ques_link', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
