# Generated by Django 2.1.5 on 2019-03-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer_user_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
