# Generated by Django 2.1.5 on 2019-03-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_max_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
