# Generated by Django 2.1.5 on 2019-03-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_category_categoryno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, default='Subjective', max_length=250, null=True, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryNo',
            field=models.IntegerField(default=1),
        ),
    ]
