# Generated by Django 2.1.5 on 2019-03-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20190331_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryNo',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Category'),
        ),
    ]
